markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 
redcarpet:


paginate: 15
paginate_path: "page:num"

# presonal config
title: 弦歌雅意的小屋
description: Erik Lu's Blog, powered by Jekyll...
author: Erik Lu

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:



