markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 
redcarpet:
extensions:
- with_toc_data
- hard_wrap
- no_intra_emphasis
- tables
- fenced_code_blocks
- autolink

paginate: 15
paginate_path: "page:num"

# presonal config
title: 弦歌雅意的小屋
description: Erik Lu's Blog, powered by Jekyll...
author: Erik Lu

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:



